name: Build Moviepilot-Frontend v3

on:
  workflow_dispatch:
  push:
    branches:
      - v3
    paths:
      - 'package.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Release version
        id: release_version
        run: |
          frontend_version=$(jq -r '.version' package.json)
          echo "frontend_version=v$frontend_version" >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable project Yarn version
        run: |
          corepack enable
          corepack install --global yarn@1.22.22

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Download Icons
        run: |
          pwd
          curl -fsSL --retry 3 "https://github.com/jxxghp/MoviePilot-Plugins/archive/refs/heads/main.zip" | busybox unzip -d /tmp -
          mv /tmp/MoviePilot-Plugins-main/icons public/plugin_icon
          rm -rf /tmp/MoviePilot-Plugins-main

      - name: Build frontend
        id: build_frontend
        run: |
          yarn build
          echo "$frontend_version" > dist/version.txt
          zip -r dist.zip dist

      - name: Delete Release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        continue-on-error: true
        with:
          tag_name: ${{ env.frontend_version }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.frontend_version }}
          name: ${{ env.frontend_version }}
          draft: false
          prerelease: false
          make_latest: true
          files: |
            dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
